// Copyright © 2022. All rights reserved.

//
// Package containing definitions for OS API protobuf messages and gRPC services,
// as well as related structures and parsing functions. Most of the code in this
// package is autogenerated by the `codegen` tool.
//
package api
