// Code generated by codegen. DO NOT EDIT.
package api

import (
	api_api_v0 "alt-os/api/api/v0"
	api_os_container_bundle_v0 "alt-os/api/os/container/bundle/v0"
	api_os_container_runtime_v0 "alt-os/api/os/container/runtime/v0"
	"errors"

	"github.com/gogo/protobuf/proto"
)

// unmarshalKind unmarshals the specified bytes to the specified message kind.
func unmarshalKind(kind, version string, value []byte) (proto.Message, error) {
	doUnmarshal := func(msg proto.Message) (proto.Message, error) {
		if err := proto.Unmarshal(value, msg); err != nil {
			return nil, err
		}
		return msg, nil
	}
	kindVersion := kind + "/" + version
	switch kindVersion {
	default:
		return nil, errors.New("unrecognized message kind/version: " + kindVersion)

	case "api.ApiMessage/v0":
		return doUnmarshal(&api_api_v0.ApiMessage{})

	case "api.ApiMessageList/v0":
		return doUnmarshal(&api_api_v0.ApiMessageList{})

	case "os.container.bundle.ApiServeRequest/v0":
		return doUnmarshal(&api_os_container_bundle_v0.ApiServeRequest{})

	case "os.container.bundle.ApiUnserveRequest/v0":
		return doUnmarshal(&api_os_container_bundle_v0.ApiUnserveRequest{})

	case "os.container.bundle.CreateRequest/v0":
		return doUnmarshal(&api_os_container_bundle_v0.CreateRequest{})

	case "os.container.runtime.ApiServeRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.ApiServeRequest{})

	case "os.container.runtime.ApiUnserveRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.ApiUnserveRequest{})

	case "os.container.runtime.ListRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.ListRequest{})

	case "os.container.runtime.ListResponse/v0":
		return doUnmarshal(&api_os_container_runtime_v0.ListResponse{})

	case "os.container.runtime.QueryStateRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.QueryStateRequest{})

	case "os.container.runtime.QueryStateResponse/v0":
		return doUnmarshal(&api_os_container_runtime_v0.QueryStateResponse{})

	case "os.container.runtime.CreateRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.CreateRequest{})

	case "os.container.runtime.StartRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.StartRequest{})

	case "os.container.runtime.KillRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.KillRequest{})

	case "os.container.runtime.DeleteRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.DeleteRequest{})
	}
}

// marshalKind marshals the specified message to a slice of bytes with the kind and version.
func marshalKind(msg proto.Message) (kind, version string, bytes []byte, err error) {
	doMarshal := func(kind, version string, msg proto.Message) (string, string, []byte, error) {
		if bytes, err := proto.Marshal(msg); err != nil {
			return "", "", nil, err
		} else {
			return kind, version, bytes, nil
		}
	}
	switch msg.(type) {
	default:
		return "", "", nil, errors.New("unrecognized message type")

	case *api_api_v0.ApiMessage:
		return doMarshal("api.ApiMessage", "v0", msg)

	case *api_api_v0.ApiMessageList:
		return doMarshal("api.ApiMessageList", "v0", msg)

	case *api_os_container_bundle_v0.ApiServeRequest:
		return doMarshal("os.container.bundle.ApiServeRequest", "v0", msg)

	case *api_os_container_bundle_v0.ApiUnserveRequest:
		return doMarshal("os.container.bundle.ApiUnserveRequest", "v0", msg)

	case *api_os_container_bundle_v0.CreateRequest:
		return doMarshal("os.container.bundle.CreateRequest", "v0", msg)

	case *api_os_container_runtime_v0.ApiServeRequest:
		return doMarshal("os.container.runtime.ApiServeRequest", "v0", msg)

	case *api_os_container_runtime_v0.ApiUnserveRequest:
		return doMarshal("os.container.runtime.ApiUnserveRequest", "v0", msg)

	case *api_os_container_runtime_v0.ListRequest:
		return doMarshal("os.container.runtime.ListRequest", "v0", msg)

	case *api_os_container_runtime_v0.ListResponse:
		return doMarshal("os.container.runtime.ListResponse", "v0", msg)

	case *api_os_container_runtime_v0.QueryStateRequest:
		return doMarshal("os.container.runtime.QueryStateRequest", "v0", msg)

	case *api_os_container_runtime_v0.QueryStateResponse:
		return doMarshal("os.container.runtime.QueryStateResponse", "v0", msg)

	case *api_os_container_runtime_v0.CreateRequest:
		return doMarshal("os.container.runtime.CreateRequest", "v0", msg)

	case *api_os_container_runtime_v0.StartRequest:
		return doMarshal("os.container.runtime.StartRequest", "v0", msg)

	case *api_os_container_runtime_v0.KillRequest:
		return doMarshal("os.container.runtime.KillRequest", "v0", msg)

	case *api_os_container_runtime_v0.DeleteRequest:
		return doMarshal("os.container.runtime.DeleteRequest", "v0", msg)
	}
}
