// Code generated by codegen. DO NOT EDIT.
package api

import (
	api_api_v0 "alt-os/api/api/v0"
	api_ctrt_v0 "alt-os/api/ctrt/v0"
	"errors"

	"github.com/gogo/protobuf/proto"
)

// unmarshalKind unmarshals the specified bytes to the specified message kind.
func unmarshalKind(kind, version string, value []byte) (proto.Message, error) {
	doUnmarshal := func(msg proto.Message) (proto.Message, error) {
		if err := proto.Unmarshal(value, msg); err != nil {
			return nil, err
		}
		return msg, nil
	}
	kindVersion := kind + "/" + version
	switch kindVersion {
	default:
		return nil, errors.New("unrecognized message kind/version: " + kindVersion)
	case "api.api.ApiMessage/v0":
		return doUnmarshal(&api_api_v0.ApiMessage{})
	case "api.api.ApiMessageList/v0":
		return doUnmarshal(&api_api_v0.ApiMessageList{})
	case "api.ctrt.ApiServeRequest/v0":
		return doUnmarshal(&api_ctrt_v0.ApiServeRequest{})
	case "api.ctrt.ApiUnserveRequest/v0":
		return doUnmarshal(&api_ctrt_v0.ApiUnserveRequest{})
	case "api.ctrt.ListRequest/v0":
		return doUnmarshal(&api_ctrt_v0.ListRequest{})
	case "api.ctrt.ListResponse/v0":
		return doUnmarshal(&api_ctrt_v0.ListResponse{})
	case "api.ctrt.QueryStateRequest/v0":
		return doUnmarshal(&api_ctrt_v0.QueryStateRequest{})
	case "api.ctrt.QueryStateResponse/v0":
		return doUnmarshal(&api_ctrt_v0.QueryStateResponse{})
	case "api.ctrt.CreateRequest/v0":
		return doUnmarshal(&api_ctrt_v0.CreateRequest{})
	case "api.ctrt.StartRequest/v0":
		return doUnmarshal(&api_ctrt_v0.StartRequest{})
	case "api.ctrt.KillRequest/v0":
		return doUnmarshal(&api_ctrt_v0.KillRequest{})
	case "api.ctrt.DeleteRequest/v0":
		return doUnmarshal(&api_ctrt_v0.DeleteRequest{})
	}
}

// marshalKind marshals the specified message to a slice of bytes with the kind and version.
func marshalKind(msg proto.Message) (kind, version string, bytes []byte, err error) {
	doMarshal := func(kind, version string, msg proto.Message) (string, string, []byte, error) {
		if bytes, err := proto.Marshal(msg); err != nil {
			return "", "", nil, err
		} else {
			return kind, version, bytes, nil
		}
	}
	switch msg.(type) {
	default:
		return "", "", nil, errors.New("unrecognized message type")
	case *api_api_v0.ApiMessage:
		return doMarshal("api.api.ApiMessage", "v0", msg)
	case *api_api_v0.ApiMessageList:
		return doMarshal("api.api.ApiMessageList", "v0", msg)
	case *api_ctrt_v0.ApiServeRequest:
		return doMarshal("api.ctrt.ApiServeRequest", "v0", msg)
	case *api_ctrt_v0.ApiUnserveRequest:
		return doMarshal("api.ctrt.ApiUnserveRequest", "v0", msg)
	case *api_ctrt_v0.ListRequest:
		return doMarshal("api.ctrt.ListRequest", "v0", msg)
	case *api_ctrt_v0.ListResponse:
		return doMarshal("api.ctrt.ListResponse", "v0", msg)
	case *api_ctrt_v0.QueryStateRequest:
		return doMarshal("api.ctrt.QueryStateRequest", "v0", msg)
	case *api_ctrt_v0.QueryStateResponse:
		return doMarshal("api.ctrt.QueryStateResponse", "v0", msg)
	case *api_ctrt_v0.CreateRequest:
		return doMarshal("api.ctrt.CreateRequest", "v0", msg)
	case *api_ctrt_v0.StartRequest:
		return doMarshal("api.ctrt.StartRequest", "v0", msg)
	case *api_ctrt_v0.KillRequest:
		return doMarshal("api.ctrt.KillRequest", "v0", msg)
	case *api_ctrt_v0.DeleteRequest:
		return doMarshal("api.ctrt.DeleteRequest", "v0", msg)
	}
}
