// Code generated by codegen. DO NOT EDIT.
package api

import (
	api_api_v0 "alt-os/api/api/v0"
	api_os_build_v0 "alt-os/api/os/build/v0"
	api_os_container_bundle_v0 "alt-os/api/os/container/bundle/v0"
	api_os_container_process_v0 "alt-os/api/os/container/process/v0"
	api_os_container_runtime_v0 "alt-os/api/os/container/runtime/v0"
	api_os_container_volume_v0 "alt-os/api/os/container/volume/v0"
	api_os_machine_image_v0 "alt-os/api/os/machine/image/v0"
	api_os_machine_runtime_v0 "alt-os/api/os/machine/runtime/v0"
	"errors"

	"github.com/gogo/protobuf/proto"
)

// unmarshalKind unmarshals the specified bytes to the specified message kind.
func unmarshalKind(kind, version string, value []byte) (proto.Message, error) {
	doUnmarshal := func(msg proto.Message) (proto.Message, error) {
		if err := proto.Unmarshal(value, msg); err != nil {
			return nil, err
		}
		return msg, nil
	}
	kindVersion := kind + "/" + version
	switch kindVersion {
	default:
		return nil, errors.New("unrecognized message kind/version: " + kindVersion)

	case "api.ApiMessage/v0":
		return doUnmarshal(&api_api_v0.ApiMessage{})

	case "api.ApiMessageList/v0":
		return doUnmarshal(&api_api_v0.ApiMessageList{})

	case "os.build.BuildConfiguration/v0":
		return doUnmarshal(&api_os_build_v0.BuildConfiguration{})

	case "os.build.BuildProfile/v0":
		return doUnmarshal(&api_os_build_v0.BuildProfile{})

	case "os.build.DependencyConfiguration/v0":
		return doUnmarshal(&api_os_build_v0.DependencyConfiguration{})

	case "os.build.Edk2Configuration/v0":
		return doUnmarshal(&api_os_build_v0.Edk2Configuration{})

	case "os.build.AcpicaConfiguration/v0":
		return doUnmarshal(&api_os_build_v0.AcpicaConfiguration{})

	case "os.build.BuildInfo/v0":
		return doUnmarshal(&api_os_build_v0.BuildInfo{})

	case "os.build.ScmSnapshot/v0":
		return doUnmarshal(&api_os_build_v0.ScmSnapshot{})

	case "os.container.bundle.ApiServeRequest/v0":
		return doUnmarshal(&api_os_container_bundle_v0.ApiServeRequest{})

	case "os.container.bundle.ApiUnserveRequest/v0":
		return doUnmarshal(&api_os_container_bundle_v0.ApiUnserveRequest{})

	case "os.container.bundle.CreateRequest/v0":
		return doUnmarshal(&api_os_container_bundle_v0.CreateRequest{})

	case "os.container.bundle.Bundle/v0":
		return doUnmarshal(&api_os_container_bundle_v0.Bundle{})

	case "os.container.process.ContainerProcess/v0":
		return doUnmarshal(&api_os_container_process_v0.ContainerProcess{})

	case "os.container.process.Terminal/v0":
		return doUnmarshal(&api_os_container_process_v0.Terminal{})

	case "os.container.process.EnvironmentVariable/v0":
		return doUnmarshal(&api_os_container_process_v0.EnvironmentVariable{})

	case "os.container.process.ResourceLimit/v0":
		return doUnmarshal(&api_os_container_process_v0.ResourceLimit{})

	case "os.container.process.Capabilities/v0":
		return doUnmarshal(&api_os_container_process_v0.Capabilities{})

	case "os.container.process.User/v0":
		return doUnmarshal(&api_os_container_process_v0.User{})

	case "os.container.runtime.ApiServeRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.ApiServeRequest{})

	case "os.container.runtime.ApiUnserveRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.ApiUnserveRequest{})

	case "os.container.runtime.ListRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.ListRequest{})

	case "os.container.runtime.ListResponse/v0":
		return doUnmarshal(&api_os_container_runtime_v0.ListResponse{})

	case "os.container.runtime.QueryStateRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.QueryStateRequest{})

	case "os.container.runtime.QueryStateResponse/v0":
		return doUnmarshal(&api_os_container_runtime_v0.QueryStateResponse{})

	case "os.container.runtime.CreateRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.CreateRequest{})

	case "os.container.runtime.StartRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.StartRequest{})

	case "os.container.runtime.KillRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.KillRequest{})

	case "os.container.runtime.DeleteRequest/v0":
		return doUnmarshal(&api_os_container_runtime_v0.DeleteRequest{})

	case "os.container.volume.ContainerVolume/v0":
		return doUnmarshal(&api_os_container_volume_v0.ContainerVolume{})

	case "os.machine.image.ApiServeRequest/v0":
		return doUnmarshal(&api_os_machine_image_v0.ApiServeRequest{})

	case "os.machine.image.ApiUnserveRequest/v0":
		return doUnmarshal(&api_os_machine_image_v0.ApiUnserveRequest{})

	case "os.machine.image.CreateRequest/v0":
		return doUnmarshal(&api_os_machine_image_v0.CreateRequest{})

	case "os.machine.image.VirtualMachine/v0":
		return doUnmarshal(&api_os_machine_image_v0.VirtualMachine{})

	case "os.machine.image.Video/v0":
		return doUnmarshal(&api_os_machine_image_v0.Video{})

	case "os.machine.image.Audio/v0":
		return doUnmarshal(&api_os_machine_image_v0.Audio{})

	case "os.machine.image.StorageDevice/v0":
		return doUnmarshal(&api_os_machine_image_v0.StorageDevice{})

	case "os.machine.image.NetworkDevice/v0":
		return doUnmarshal(&api_os_machine_image_v0.NetworkDevice{})

	case "os.machine.image.SerialDevice/v0":
		return doUnmarshal(&api_os_machine_image_v0.SerialDevice{})

	case "os.machine.runtime.ApiServeRequest/v0":
		return doUnmarshal(&api_os_machine_runtime_v0.ApiServeRequest{})

	case "os.machine.runtime.ApiUnserveRequest/v0":
		return doUnmarshal(&api_os_machine_runtime_v0.ApiUnserveRequest{})

	case "os.machine.runtime.ListRequest/v0":
		return doUnmarshal(&api_os_machine_runtime_v0.ListRequest{})

	case "os.machine.runtime.ListResponse/v0":
		return doUnmarshal(&api_os_machine_runtime_v0.ListResponse{})

	case "os.machine.runtime.QueryStateRequest/v0":
		return doUnmarshal(&api_os_machine_runtime_v0.QueryStateRequest{})

	case "os.machine.runtime.QueryStateResponse/v0":
		return doUnmarshal(&api_os_machine_runtime_v0.QueryStateResponse{})

	case "os.machine.runtime.CreateRequest/v0":
		return doUnmarshal(&api_os_machine_runtime_v0.CreateRequest{})

	case "os.machine.runtime.StartRequest/v0":
		return doUnmarshal(&api_os_machine_runtime_v0.StartRequest{})

	case "os.machine.runtime.KillRequest/v0":
		return doUnmarshal(&api_os_machine_runtime_v0.KillRequest{})

	case "os.machine.runtime.DeleteRequest/v0":
		return doUnmarshal(&api_os_machine_runtime_v0.DeleteRequest{})

	case "os.machine.runtime.DeployRequest/v0":
		return doUnmarshal(&api_os_machine_runtime_v0.DeployRequest{})
	}
}

// marshalKind marshals the specified message to a slice of bytes with the kind and version.
func marshalKind(msg proto.Message) (kind, version string, bytes []byte, err error) {
	doMarshal := func(kind, version string, msg proto.Message) (string, string, []byte, error) {
		if bytes, err := proto.Marshal(msg); err != nil {
			return "", "", nil, err
		} else {
			return kind, version, bytes, nil
		}
	}
	switch msg.(type) {
	default:
		return "", "", nil, errors.New("unrecognized message type")

	case *api_api_v0.ApiMessage:
		return doMarshal("api.ApiMessage", "v0", msg)

	case *api_api_v0.ApiMessageList:
		return doMarshal("api.ApiMessageList", "v0", msg)

	case *api_os_build_v0.BuildConfiguration:
		return doMarshal("os.build.BuildConfiguration", "v0", msg)

	case *api_os_build_v0.BuildProfile:
		return doMarshal("os.build.BuildProfile", "v0", msg)

	case *api_os_build_v0.DependencyConfiguration:
		return doMarshal("os.build.DependencyConfiguration", "v0", msg)

	case *api_os_build_v0.Edk2Configuration:
		return doMarshal("os.build.Edk2Configuration", "v0", msg)

	case *api_os_build_v0.AcpicaConfiguration:
		return doMarshal("os.build.AcpicaConfiguration", "v0", msg)

	case *api_os_build_v0.BuildInfo:
		return doMarshal("os.build.BuildInfo", "v0", msg)

	case *api_os_build_v0.ScmSnapshot:
		return doMarshal("os.build.ScmSnapshot", "v0", msg)

	case *api_os_container_bundle_v0.ApiServeRequest:
		return doMarshal("os.container.bundle.ApiServeRequest", "v0", msg)

	case *api_os_container_bundle_v0.ApiUnserveRequest:
		return doMarshal("os.container.bundle.ApiUnserveRequest", "v0", msg)

	case *api_os_container_bundle_v0.CreateRequest:
		return doMarshal("os.container.bundle.CreateRequest", "v0", msg)

	case *api_os_container_bundle_v0.Bundle:
		return doMarshal("os.container.bundle.Bundle", "v0", msg)

	case *api_os_container_process_v0.ContainerProcess:
		return doMarshal("os.container.process.ContainerProcess", "v0", msg)

	case *api_os_container_process_v0.Terminal:
		return doMarshal("os.container.process.Terminal", "v0", msg)

	case *api_os_container_process_v0.EnvironmentVariable:
		return doMarshal("os.container.process.EnvironmentVariable", "v0", msg)

	case *api_os_container_process_v0.ResourceLimit:
		return doMarshal("os.container.process.ResourceLimit", "v0", msg)

	case *api_os_container_process_v0.Capabilities:
		return doMarshal("os.container.process.Capabilities", "v0", msg)

	case *api_os_container_process_v0.User:
		return doMarshal("os.container.process.User", "v0", msg)

	case *api_os_container_runtime_v0.ApiServeRequest:
		return doMarshal("os.container.runtime.ApiServeRequest", "v0", msg)

	case *api_os_container_runtime_v0.ApiUnserveRequest:
		return doMarshal("os.container.runtime.ApiUnserveRequest", "v0", msg)

	case *api_os_container_runtime_v0.ListRequest:
		return doMarshal("os.container.runtime.ListRequest", "v0", msg)

	case *api_os_container_runtime_v0.ListResponse:
		return doMarshal("os.container.runtime.ListResponse", "v0", msg)

	case *api_os_container_runtime_v0.QueryStateRequest:
		return doMarshal("os.container.runtime.QueryStateRequest", "v0", msg)

	case *api_os_container_runtime_v0.QueryStateResponse:
		return doMarshal("os.container.runtime.QueryStateResponse", "v0", msg)

	case *api_os_container_runtime_v0.CreateRequest:
		return doMarshal("os.container.runtime.CreateRequest", "v0", msg)

	case *api_os_container_runtime_v0.StartRequest:
		return doMarshal("os.container.runtime.StartRequest", "v0", msg)

	case *api_os_container_runtime_v0.KillRequest:
		return doMarshal("os.container.runtime.KillRequest", "v0", msg)

	case *api_os_container_runtime_v0.DeleteRequest:
		return doMarshal("os.container.runtime.DeleteRequest", "v0", msg)

	case *api_os_container_volume_v0.ContainerVolume:
		return doMarshal("os.container.volume.ContainerVolume", "v0", msg)

	case *api_os_machine_image_v0.ApiServeRequest:
		return doMarshal("os.machine.image.ApiServeRequest", "v0", msg)

	case *api_os_machine_image_v0.ApiUnserveRequest:
		return doMarshal("os.machine.image.ApiUnserveRequest", "v0", msg)

	case *api_os_machine_image_v0.CreateRequest:
		return doMarshal("os.machine.image.CreateRequest", "v0", msg)

	case *api_os_machine_image_v0.VirtualMachine:
		return doMarshal("os.machine.image.VirtualMachine", "v0", msg)

	case *api_os_machine_image_v0.Video:
		return doMarshal("os.machine.image.Video", "v0", msg)

	case *api_os_machine_image_v0.Audio:
		return doMarshal("os.machine.image.Audio", "v0", msg)

	case *api_os_machine_image_v0.StorageDevice:
		return doMarshal("os.machine.image.StorageDevice", "v0", msg)

	case *api_os_machine_image_v0.NetworkDevice:
		return doMarshal("os.machine.image.NetworkDevice", "v0", msg)

	case *api_os_machine_image_v0.SerialDevice:
		return doMarshal("os.machine.image.SerialDevice", "v0", msg)

	case *api_os_machine_runtime_v0.ApiServeRequest:
		return doMarshal("os.machine.runtime.ApiServeRequest", "v0", msg)

	case *api_os_machine_runtime_v0.ApiUnserveRequest:
		return doMarshal("os.machine.runtime.ApiUnserveRequest", "v0", msg)

	case *api_os_machine_runtime_v0.ListRequest:
		return doMarshal("os.machine.runtime.ListRequest", "v0", msg)

	case *api_os_machine_runtime_v0.ListResponse:
		return doMarshal("os.machine.runtime.ListResponse", "v0", msg)

	case *api_os_machine_runtime_v0.QueryStateRequest:
		return doMarshal("os.machine.runtime.QueryStateRequest", "v0", msg)

	case *api_os_machine_runtime_v0.QueryStateResponse:
		return doMarshal("os.machine.runtime.QueryStateResponse", "v0", msg)

	case *api_os_machine_runtime_v0.CreateRequest:
		return doMarshal("os.machine.runtime.CreateRequest", "v0", msg)

	case *api_os_machine_runtime_v0.StartRequest:
		return doMarshal("os.machine.runtime.StartRequest", "v0", msg)

	case *api_os_machine_runtime_v0.KillRequest:
		return doMarshal("os.machine.runtime.KillRequest", "v0", msg)

	case *api_os_machine_runtime_v0.DeleteRequest:
		return doMarshal("os.machine.runtime.DeleteRequest", "v0", msg)

	case *api_os_machine_runtime_v0.DeployRequest:
		return doMarshal("os.machine.runtime.DeployRequest", "v0", msg)
	}
}
